var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('transition',{attrs:{"name":"fade"}},[(_vm.isShow)?_c('div',{staticClass:"color-picker-container",style:(_vm.stylePosition),on:{"click":function($event){return _vm.onClickContainer()}}},[_c('div',{staticClass:"tab-header"},[_c('div',{staticClass:"header-item",class:{ 'header-item-active': _vm.indexHeaderActive == 0 },on:{"click":function($event){_vm.indexHeaderActive = 0}}},[_c('span',{staticClass:"fs-12"},[_vm._v("Color picker")])]),_vm._v(" "),_c('div',{staticClass:"header-item",class:{ 'header-item-active': _vm.indexHeaderActive == 1 },on:{"click":function($event){_vm.indexHeaderActive = 1}}},[_c('span',{staticClass:"fs-12"},[_vm._v("Palettes")])])]),_vm._v(" "),_c('div',{staticClass:"item-divide"}),_vm._v(" "),_c('div',{staticClass:"wrapper-content text-left"},[(_vm.indexHeaderActive === 0)?_c('div',[_c('span',{staticClass:"text-title-color"},[_vm._v("All Colors")]),_vm._v(" "),_c('div',{staticClass:"wrapper-item-color"},_vm._l((_vm.listColorPicker),function(color,index){return _c('div',{key:index,staticClass:"item-color",style:(("background-color: " + (color.hex) + "; border: " + (index === 1 ? '1px solid grey' : 'none'))),on:{"click":function($event){return _vm.onChooseColor(color)}}})}),0)]):_c('div',{staticClass:"wrapper-item-color"},_vm._l((_vm.listColorPalettes),function(color,index){return _c('div',{key:index,staticClass:"item-color",style:(("background-color: " + (color.hex) + ";")),on:{"click":function($event){return _vm.onChooseColor(color)}}})}),0)]),_vm._v(" "),_c('div',{staticClass:"opacity"},[_c('div',{staticClass:"title-opacity"},[_c('span',{staticStyle:{"font-weight":"600","color":"rgb(55, 64, 70)","font-size":"14px"}},[_vm._v("Opacity")]),_vm._v(" "),_c('span',{staticStyle:{"font-weight":"400","color":"rgb(99, 109, 116)","font-size":"14px"}},[_vm._v(_vm._s(_vm.colorSelected.opacity)+"%")])]),_vm._v(" "),_c('div',[_c('vue-slider',{staticClass:"opacity-slider",staticStyle:{"flex":"1"},attrs:{"value":_vm.colorSelected.opacity,"min":0,"max":100,"step":1,"tooltip":"none","dotSize":"16"},on:{"change":_vm.onChangeOpacity}})],1)]),_vm._v(" "),_c('div',{staticClass:"input-custom"},[_c('span',{staticClass:"dot-preview",style:(("background-color: " + _vm.getColorPreview))}),_vm._v(" "),_c('input',{directives:[{name:"model",rawName:"v-model",value:(_vm.colorSelected.hex),expression:"colorSelected.hex"}],staticClass:"mx-2 input-hex",staticStyle:{"width":"150px","border":"none"},attrs:{"type":"text"},domProps:{"value":(_vm.colorSelected.hex)},on:{"input":[function($event){if($event.target.composing){ return; }_vm.$set(_vm.colorSelected, "hex", $event.target.value)},_vm.onChangeCustom]}}),_vm._v(" "),_c('span',{staticClass:"label-hex"},[_vm._v("hex")])])]):_vm._e()])}
var staticRenderFns = []
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-f3c921c0","hasScoped":true,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/screens/SimpleEdit/ColorPickerCustom.vue
// module id = null
// module chunks = 