var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('v-dialog',{attrs:{"content-class":"radius-20","max-width":"500px","persistent":_vm.isLoading,"scrollable":""},model:{value:(_vm.showDialog),callback:function ($$v) {_vm.showDialog=$$v},expression:"showDialog"}},[_c('v-card',[_c('v-card-title',{staticClass:"mt-2"},[_c('div',{staticClass:"text-center",staticStyle:{"flex":"1"}},[_c('h3',{staticClass:"font-weight-bold"},[_vm._v("\n          Tạo Profile\n        ")])]),_vm._v(" "),_c('v-btn',{staticStyle:{"position":"absolute","right":"10px","top":"10px"},attrs:{"icon":""},on:{"click":function($event){_vm.showDialog = false}}},[_c('v-icon',[_vm._v("mdi-close")])],1)],1),_vm._v(" "),_c('v-divider'),_vm._v(" "),_c('v-card-text',[_c('div',{staticClass:"d-flex align-center"},[_c('span',{staticClass:"black-text font-weight-bold fs-16 mr-4"},[_vm._v("Tên Profile:")]),_vm._v(" "),_c('v-text-field',{attrs:{"placeholder":"Nhập tên Profile"},model:{value:(_vm.profile.name),callback:function ($$v) {_vm.$set(_vm.profile, "name", $$v)},expression:"profile.name"}})],1),_vm._v(" "),_c('div',{staticClass:"d-flex align-center"},[_c('span',{staticClass:"black-text font-weight-bold fs-16 mr-4"},[_vm._v("Độ phân giải:")]),_vm._v(" "),_c('v-text-field',{staticClass:"mr-5",staticStyle:{"width":"50px"},attrs:{"label":"Width","placeholder":"Nhập Width: (VD: 1280)","max":"8000","min":"1","type":"number"},model:{value:(_vm.profile.width),callback:function ($$v) {_vm.$set(_vm.profile, "width", $$v)},expression:"profile.width"}}),_vm._v(" "),_c('span',{staticClass:"black-text font-weight-bold fs-16 mr-4"},[_vm._v("X")]),_vm._v(" "),_c('v-text-field',{attrs:{"label":"Height","placeholder":"Nhập height: (VD: 720)","max":"8000","min":"1","type":"number"},model:{value:(_vm.profile.height),callback:function ($$v) {_vm.$set(_vm.profile, "height", $$v)},expression:"profile.height"}})],1)]),_vm._v(" "),_c('v-card-actions',{staticClass:"d-block text-center pb-5"},[_c('v-btn',{staticClass:"mx-2 px-8",attrs:{"color":"primary","loading":_vm.isLoading},on:{"click":_vm.onCreateClick}},[_vm._v("Tạo")])],1)],1)],1)}
var staticRenderFns = []
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-685a69a4","hasScoped":true,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/ModalCreateProfile.vue
// module id = null
// module chunks = 