var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"text-center"},[_c('v-dialog',{attrs:{"max-width":"700px","scrollable":""},model:{value:(_vm.showDialog),callback:function ($$v) {_vm.showDialog=$$v},expression:"showDialog"}},[_c('v-card',[_c('v-card-title',{staticClass:"d-block"},[_c('div',{staticClass:"d-flex"},[_c('div',{staticClass:"text-center",staticStyle:{"flex":"1"}},[_c('h2',{staticClass:" font-weight-bold"},[_vm._v("Nạp Tiền")])]),_vm._v(" "),_c('v-btn',{staticStyle:{"position":"absolute","right":"10px"},attrs:{"icon":""},on:{"click":function($event){_vm.showDialog = false}}},[_c('v-icon',[_vm._v("mdi-close")])],1)],1),_vm._v(" "),_c('div',{staticClass:"font-weight-bold"},[_c('h5',[_vm._v("Lựa chọn phương thức thanh toán:")])])]),_vm._v(" "),_c('v-card-text',{staticStyle:{"color":"#000 !important"}},[_c('v-row',_vm._l((_vm.listPaymentMethod),function(bank,index){return _c('v-col',{key:index,attrs:{"cols":"auto"}},[_c('v-card',{class:{
                payment_selected: _vm.paymentSelected.bank === bank.bank
              },staticStyle:{"padding":"5px","border":"1px solid gray","border-radius":"5px"},style:(bank.style)},[_c('img',{staticStyle:{"height":"50px","width":"120px","border-radius":"10px","cursor":"pointer"},attrs:{"src":bank.icon,"alt":""},on:{"click":function($event){return _vm.onSelectPayment(bank)}}})])],1)}),1),_vm._v(" "),_c('h3',{staticClass:"mt-3"},[_vm._v("Thông tin thanh toán:")]),_vm._v(" "),_c('v-list',{staticClass:"font-weight-bold"},[_c('v-list-item',[_c('v-col',[_vm._v("Phương thức thanh toán")]),_vm._v(" "),_c('v-col',{staticStyle:{"color":"green !important"}},[_vm._v("\n              "+_vm._s(_vm.paymentSelected.bankName))])],1),_vm._v(" "),_c('v-divider'),_vm._v(" "),_c('v-list-item',[_c('v-col',[_vm._v("Số tài khoản")]),_vm._v(" "),_c('v-col',{staticStyle:{"color":"red !important"}},[_vm._v("\n              "+_vm._s(_vm.paymentSelected.user_stk))])],1),_vm._v(" "),_c('v-divider'),_vm._v(" "),_c('v-list-item',[_c('v-col',[_vm._v("Người thụ hưởng")]),_vm._v(" "),_c('v-col',{staticClass:"text-text-uppercase"},[_vm._v("\n              "+_vm._s(_vm.paymentSelected.user_name))])],1),_vm._v(" "),_c('v-divider'),_vm._v(" "),_c('v-list-item',[_c('v-col',[_vm._v("Số tiền")]),_vm._v(" "),_c('v-col',[_vm._v("\n              "+_vm._s(_vm.packageSelected
                  ? _vm.packageSelected.price.toLocaleString("it-IT")
                  : "100.000 ")+"\n              "),_c('span',{staticStyle:{"color":"black","font-weight":"bold"}},[_vm._v("VNĐ ")]),_vm._v(" "),_c('span',{staticStyle:{"color":"red !important"}},[_vm._v("(Nạp tối thiểu 100.000)")])])],1),_vm._v(" "),_c('v-divider'),_vm._v(" "),_c('v-list-item',[_c('v-col',[_vm._v("Nội dung chuyển tiền")]),_vm._v(" "),_c('v-col',{staticStyle:{"color":"green !important"}},[_vm._v("\n              "+_vm._s(_vm.packageSelected
                  ? _vm.paymentSelected.description
                  : "NAP" + _vm.paymentSelected.description)+"\n              "),_c('span',{staticStyle:{"color":"red !important"}},[_vm._v("(Viết In Hoa - Không Cách)")])])],1)],1),_vm._v(" "),_c('div',[_c('span',{staticClass:"font-weight-bold"},[_c('span',{staticStyle:{"color":"red","font-size":"20px"}},[_vm._v("*")]),_vm._v(" Lưu ý:")]),_vm._v(" "),_c('p',{staticClass:"m-0"},[_vm._v("\n            - Chuyển khoản theo hình thức\n            "),_c('span',{staticClass:"font-weight-bold"},[_vm._v("24/7.")])]),_vm._v(" "),_c('p',{staticClass:"m-0"},[_vm._v("- Lưu lại hình ảnh chuyển khoản.")]),_vm._v(" "),_c('p',{staticClass:"m-0"},[_vm._v("- Không hoàn tiền bất kỳ lí do nào.")]),_vm._v(" "),_c('p',{staticClass:"m-0"},[_vm._v("\n            - Hệ thống sẽ tự động cập nhật trong vòng 1 -> 5 phút. Nếu quá 5\n            phút chưa thấy tài khoản được cập nhật. Hãy liên hệ với\n            "),_c('a',{staticStyle:{"font-weight":"bold"},attrs:{"target":"_blank","href":"https://www.facebook.com/106506441311541"}},[_vm._v("Đội ngũ hỗ trợ")]),_vm._v("\n            để giải quyết.!\n          ")])])],1)],1)],1)],1)}
var staticRenderFns = []
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-21ce622c","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/components/ModalPayment.vue
// module id = null
// module chunks = 