var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('v-container',{attrs:{"fluid":""}},[_c('div',[_c('v-card',{staticClass:"mx-auto",attrs:{"loading":_vm.loading > 0}},[_c('toolbar',{attrs:{"path":_vm.path,"storage":_vm.activeStorage,"itemActive":_vm.itemActive},on:{"storage-changed":_vm.storageChanged,"path-changed":_vm.pathChanged,"add-files":_vm.addUploadingFiles,"folder-created":function($event){_vm.refreshPending = true},"loading":_vm.loadingChanged}}),_vm._v(" "),_c('div',{staticClass:"d-flex flex-row"},[_c('div',{staticStyle:{"flex":"1 0 300px","overflow":"auto"}},[_c('tree',{attrs:{"typeFileTarget":_vm.typeFileTarget,"path":_vm.path,"storage":_vm.activeStorage,"icons":_vm.icons,"refreshPending":_vm.refreshPending,"itemActive":_vm.itemActive},on:{"path-changed":_vm.pathChanged,"loading":_vm.loadingChanged,"refreshed":function($event){_vm.refreshPending = false},"setItemActive":_vm.setItemActive}})],1),_vm._v(" "),(_vm.tree)?_c('v-divider',{staticStyle:{"z-index":"2"},attrs:{"vertical":""}}):_vm._e(),_vm._v(" "),_c('div',{staticStyle:{"flex":"3 0 300px"}},[_c('list',{attrs:{"typeFileTarget":_vm.typeFileTarget,"itemActive":_vm.itemActive,"path":_vm.path,"storage":_vm.activeStorage,"icons":_vm.icons,"refreshPending":_vm.refreshPending},on:{"path-changed":_vm.pathChanged,"loading":_vm.loadingChanged,"refreshed":function($event){_vm.refreshPending = false},"file-deleted":function($event){_vm.refreshPending = true}}})],1)],1),_vm._v(" "),(_vm.uploadingFiles !== false)?_c('upload',{attrs:{"path":_vm.path,"storage":_vm.activeStorage,"files":_vm.uploadingFiles,"icons":_vm.icons,"maxUploadFilesCount":_vm.maxUploadFilesCount,"maxUploadFileSize":_vm.maxUploadFileSize},on:{"add-files":_vm.addUploadingFiles,"remove-file":_vm.removeUploadingFile,"clear-files":function($event){_vm.uploadingFiles = []},"cancel":function($event){_vm.uploadingFiles = false},"uploaded":_vm.uploaded}}):_vm._e()],1)],1)])}
var staticRenderFns = []
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-bcf14dde","hasScoped":true,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/screens/UserProfile/FileManager/index.vue
// module id = null
// module chunks = 