var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('v-toolbar',{attrs:{"flat":"","dense":"","color":"blue-grey lighten-5"}},[_c('v-toolbar-items',[_c('v-btn',{attrs:{"text":""},on:{"click":function($event){return _vm.changePath('/')}}},[_c('v-icon',{staticClass:"mr-2"},[_vm._v("mdi-folder-multiple-outline")]),_vm._v("\n      "+_vm._s(_vm.storage)+"\n    ")],1),_vm._v(" "),_vm._l((_vm.pathSegments),function(segment,index){return [_c('v-icon',{key:index + '-icon'},[_vm._v("mdi-chevron-right")]),_vm._v(" "),_c('v-btn',{key:index + '-btn',attrs:{"text":"","input-value":index === _vm.pathSegments.length - 1},on:{"click":function($event){return _vm.changePath(segment.path)}}},[_vm._v(_vm._s(_vm.trimText(segment.name)))])]})],2),_vm._v(" "),_c('div',{staticClass:"flex-grow-1"}),_vm._v(" "),(_vm.$vuetify.breakpoint.smAndUp)?[(_vm.pathSegments.length > 0)?_c('v-tooltip',{attrs:{"bottom":"","open-delay":"500"},scopedSlots:_vm._u([{key:"activator",fn:function(ref){
var on = ref.on;
return [_c('v-btn',_vm._g({attrs:{"icon":""},on:{"click":_vm.goUp}},on),[_c('v-icon',[_vm._v("mdi-arrow-up-bold-outline")])],1)]}}],null,false,2998795643)},[_vm._v(" "),(_vm.pathSegments.length === 1)?_c('span',[_vm._v("Up to \"root\"")]):_c('span',[_vm._v("Up to \""+_vm._s(_vm.pathSegments[_vm.pathSegments.length - 2].name)+"\"")])]):_vm._e(),_vm._v(" "),_c('v-menu',{key:_vm.path,attrs:{"close-on-content-click":false,"nudge-width":200,"offset-y":""},scopedSlots:_vm._u([{key:"activator",fn:function(ref){
var on = ref.on;
return [(_vm.isFolder)?_c('v-btn',_vm._g({attrs:{"icon":"","title":"Create Folder"}},on),[_c('v-icon',[_vm._v("mdi-folder-plus-outline")])],1):_vm._e()]}}],null,false,2348540892),model:{value:(_vm.newFolderPopper),callback:function ($$v) {_vm.newFolderPopper=$$v},expression:"newFolderPopper"}},[_vm._v(" "),_c('v-card',[_c('v-card-text',[_c('v-text-field',{attrs:{"label":"Name","hide-details":""},model:{value:(_vm.newFolderName),callback:function ($$v) {_vm.newFolderName=$$v},expression:"newFolderName"}})],1),_vm._v(" "),_c('v-card-actions',[_c('div',{staticClass:"flex-grow-1"}),_vm._v(" "),_c('v-btn',{attrs:{"depressed":""},on:{"click":function($event){_vm.newFolderPopper = false}}},[_vm._v("Cancel")]),_vm._v(" "),_c('v-btn',{attrs:{"color":"success","disabled":!_vm.newFolderName,"depressed":""},on:{"click":_vm.mkdir}},[_vm._v("Create Folder")])],1)],1)],1),_vm._v(" "),(_vm.path && _vm.isFolder)?_c('v-btn',{attrs:{"icon":"","title":"Upload Files"},on:{"click":function($event){return _vm.$refs.inputUpload.click()}}},[_c('v-icon',[_vm._v("mdi-plus-circle")]),_vm._v(" "),_c('input',{directives:[{name:"show",rawName:"v-show",value:(false),expression:"false"}],ref:"inputUpload",attrs:{"type":"file","multiple":""},on:{"change":_vm.addFiles}})],1):_vm._e(),_vm._v(" "),(_vm.path)?_c('v-btn',{attrs:{"color":"error","icon":""},on:{"click":function($event){$event.stopPropagation();return _vm.deleteItem()}}},[_c('v-icon',[_vm._v("mdi-delete-outline")])],1):_vm._e()]:_vm._e()],2)}
var staticRenderFns = []
var esExports = { render: render, staticRenderFns: staticRenderFns }
export default esExports


//////////////////
// WEBPACK FOOTER
// ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-25766e6e","hasScoped":true,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/screens/UserProfile/FileManager/Toolbar.vue
// module id = null
// module chunks = 